### ISSUE TITLE
Compilation error after `go get github.com/haccer/subjack`

### ISSUE THREAD

**Issue by phr0nak** [haccer/subjack#11]
When compiling the latest version of `subjack` from the git. See error below:

`src/github.com/haccer/subjack/main.go:454:9: cannot use results (type chan *amass.AmassRequest) as type chan *amass.AmassOutput in field value`

**Comment by caffix** [comment]
@haccer The Amass major version change caused the output structure to be modified. You will need to update your code to use the AmassOutput structure that is defined in the amass.go file.

**Comment by haccer** [comment]
Thank you @phr0nak & @caffix!
