### ISSUE TITLE
-o output not available when installed with go get

### ISSUE THREAD

**Issue by MrThreat** [haccer/subjack#12]
Morning!

Great tool. There is an issue with the install on go get URL. Image attached below FYI. It just says its not defined.
![screenshot 2018-06-26_09-14-37](https://user-images.githubusercontent.com/32046316/41880462-82ac2dba-7921-11e8-81a8-38cc98f8c602.png)

**Comment by haccer** [comment]
@MrThreat lol I actually just realized this on my own right now, going to fix immediately

**Comment by haccer** [comment]
Added, thanks
