### ISSUE TITLE
Not Properly Installed!

### ISSUE THREAD

**Issue by Sechunt3r** [haccer/subjack#37]
Hi Sir,
Hope you are good!

Actually i download this tool via go get github,com/haccer/subjack. and i am using Ubuntu 16
then i found the location of the tools its in /src/github.com/haccer/subjack (master)> 
after that i simply run go build and it will successfully done.

But when i use this command --> subjack -w sub.txt -t 100 -timeout 30 -o results.txt -ssl 	 

it shows nothing please help me out from this!

Regards
Shivam

**Comment by haccer** [comment]
Hi @Sechunt3r - It shows nothing because no subdomain takeovers were found. You can verify this by running in verbose mode with the flag `-v`.
