### ISSUE TITLE
Error in your urls for other git repos, they have been updated.

### ISSUE THREAD

**Issue by d0xo** [haccer/subjack#39]
github.com/klauspost and the rest have updated their paths. 404 on them. Can not install.

go install
../../valyala/fasthttp/compress.go:10:2: cannot find package "github.com/klauspost/compress/flate" in any of:
	/usr/local/go/src/github.com/klauspost/compress/flate (from $GOROOT)
	/go/src/github.com/klauspost/compress/flate (from $GOPATH)
../../valyala/fasthttp/compress.go:11:2: cannot find package "github.com/klauspost/compress/gzip" in any of:
	/usr/local/go/src/github.com/klauspost/compress/gzip (from $GOROOT)
	/go/src/github.com/klauspost/compress/gzip (from $GOPATH)
../../valyala/fasthttp/compress.go:12:2: cannot find package "github.com/klauspost/compress/zlib" in any of:
	/usr/local/go/src/github.com/klauspost/compress/zlib (from $GOROOT)
	/go/src/github.com/klauspost/compress/zlib (from $GOPATH)
../../valyala/fasthttp/args.go:10:2: cannot find package "github.com/valyala/bytebufferpool" in any of:
	/usr/local/go/src/github.com/valyala/bytebufferpool (from $GOROOT)
	/go/src/github.com/valyala/bytebufferpool (from $GOPATH)

**Comment by haccer** [comment]
Run `go get -u github.com/haccer/subjack`
