### ISSUE TITLE
Error finding /src/github.com/haccer/subjack/fingerprints.json:

### ISSUE THREAD

**Issue by d1pakda5** [haccer/subjack#40]
I verified the file is available on below directory 2019/08/21 08:25:30 open /src/github.com/haccer/subjack/fingerprints.json: no such file or directory

still showing the error

**Comment by b4tc0untry** [comment]
Try running it like this,
`./subjack -w subdomains.txt -t 10 -timeout 30 -o results.txt -ssl -c ~/go/src/github.com/haccer/subjack/fingerprints.json -v`

**Comment by 0x3c3e** [comment]
@d1pakda5 actually check your GAPATH env, https://github.com/haccer/subjack/blob/99fe2fff937aa6aa3d30679c52320fb874f3eec9/main.go#L12
https://github.com/haccer/subjack/blob/99fe2fff937aa6aa3d30679c52320fb874f3eec9/main.go#L15

**Comment by sabeesh03** [comment]
-bash: ./subjack: is a directory how do i rectify it
