### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by marcelo321** [haccer/subjack#56]
Im getting this error and i don't know what it is causing it. I get normal responses in the middle but idk what is this error

`net.Error timeout=false, temp=false: read tcp [2600:3c02::f03c:92ff:fed5:7285]:52632->[2610:a0:4:1::f1de]:43: read: connection reset by peer
net.Error timeout=false, temp=false: read tcp [2600:3c02::f03c:92ff:fed5:7285]:52636->[2610:a0:4:1::f1de]:43: read: connection reset by peer
net.Error timeout=false, temp=false: read tcp [2600:3c02::f03c:92ff:fed5:7285]:52640->[2610:a0:4:1::f1de]:43: read: connection reset by peer
net.Error timeout=false, temp=false: read tcp [2600:3c02::f03c:92ff:fed5:7285]:52648->[2610:a0:4:1::f1de]:43: read: connection reset by peer
net.Error timeout=false, temp=false: read tcp [2600:3c02::f03c:92ff:fed5:7285]:52654->[2610:a0:4:1::f1de]:43: read: connection reset by peer
net.Error timeout=false, temp=false: read tcp [2600:3c02::f03c:92ff:fed5:7285]:52666->[2610:a0:4:1::f1de]:43: read: connection reset by peer
net.Error timeout=false, temp=false: read tcp [2600:3c02::f03c:92ff:fed5:7285]:52688->[2610:a0:4:1::f1de]:43: read: connection reset by peer
net.Error timeout=false, temp=false: read tcp [2600:3c02::f03c:92ff:fed5:7285]:52702->[2610:a0:4:1::f1de]:43: read: connection reset by peer
net.Error timeout=false, temp=false: read tcp [2600:3c02::f03c:92ff:fed5:7285]:52716->[2610:a0:4:1::f1de]:43: read: connection reset by peer
net.Error timeout=false, temp=false: read tcp [2600:3c02::f03c:92ff:fed5:7285]:52740->[2610:a0:4:1::f1de]:43: read: connection reset by peer
net.Error timeout=false, temp=false: read tcp [2600:3c02::f03c:92ff:fed5:7285]:52786->[2610:a0:4:1::f1de]:43: read: connection reset by peer
net.Error timeout=false, temp=false: read tcp [2600:3c02::f03c:92ff:fed5:7285]:52832->[2610:a0:4:1::f1de]:43: read: connection reset by peer
net.Error timeout=false, temp=false: read tcp [2600:3c02::f03c:92ff:fed5:7285]:52888->[2610:a0:4:1::f1de]:43: read: connection reset by peer
net.Error timeout=false, temp=false: read tcp [2600:3c02::f03c:92ff:fed5:7285]:52922->[2610:a0:4:1::f1de]:43: read: connection reset by peer`

**Comment by sumgr0** [comment]
I'm getting the same error messages too... anyone know what it means and if these can be fixed?
