### ISSUE TITLE
Subjack Fails to build when AMass is failing

### ISSUE THREAD

**Issue by codingo** [haccer/subjack#9]
I'm unable to build the current version of AMass (outlined here: https://github.com/caffix/amass/issues/36). Although I can resolve this on AMass with release tags because this is a dependency in subjack I'm unable to build that without patching AMass directly in my gopath.

It would be good to have some exception handling within subjack to allow it to continue building even in the absence of a working amass build.

**Comment by haccer** [comment]
I replied [here](https://github.com/caffix/amass/issues/36).

tl;dr you need to update your Go
