### ISSUE TITLE
subjack installed into go/bin but no reply to subjack commands

### ISSUE THREAD

**Issue by heqmat** [haccer/subjack#90]
i'm trying to run this command: `subjack -w new2.txt -t 100 -timeout 30 -o results.txt -ssl
`But there is no reply in my terminal. And it is closing in 3 seconds.

**Comment by madslaz** [comment]
Have you utilized `-v`? I found that when my subjack was returning zero response in my terminal and closing quickly, it was still performing the code but just not displaying the results.

**Comment by heqmat** [comment]
Sorry for late response, i didnt know that "-v" thanks for information. I tried and it worked thanks
